spring:
  profiles:
    active: dev # 기본 환경 선택
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true #classpath에 속해있는 파일들의 수정을 감지하고 자동으로 재시작
  jpa:
    show_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        #physical-strategy: com.castingn.config.JpaNamingStrategy
    properties:
      hibernate:
        #show_sql: true #쿼리 콘솔 출력
        format_sql: true #쿼리 이쁘게
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8080
  error:
    include-binding-errors: always #바인딩 오류를 포함시킬 때
    whitelabel:
      enabled: false #브라우저 요청에 대해 서버 오류시 기본으로 노출할 페이지를 사용할지 여부
    include-exception: false #예외 내용을 포함시킬 때
    include-message: always #오류 메시지를 포함시킬 때
    include-stacktrace: always #stacktrace를 포함시킬 떄
    path: /error #오류 처리할 컨트롤러 패스

# dev 환경
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:log4jdbc:mysql://3.37.238.95:3306/example?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: sotkfkd0!A
    dbcp2:
      validation-query: SELECT 1